# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - 3.3
  - release

before_install:
  - cd gpds
  
install:
  - R -e 'install.packages(c("devtools"))'
  - R -e 'devtools::install_dev_deps()' # might be an overkill
  - R -e 'devtools::document()'
  - R -e 'devtools::test()'

script:
  - R CMD build .
  - R CMD check *tar.gz
  
after_success:
  - Rscript -e 'covr::codecov()'