# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: python
sudo: true
cache: packages

python:
  - "3.6"

before_install:
  - sudo add-apt-repository ppa:marutter/rrutter3.5 -y
  - sudo apt-get update
  - sudo apt install r-api-3.5 -y
  - sudo apt-get install libblas-dev liblapack-dev gfortran -y
  - mkdir -p ~/R/library
  - export R_LIBS_USER=$HOME/R/library

install:
  - ./build.sh

script:
  - R CMD build rgpds
  - R CMD check rgpds*tar.gz
