# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - 3.3
  - release

before_install:
  - export CODECOV_TOKEN="7b481576-694c-4591-8370-64f61df55bdc"
  - cd gpds
  
install:
  - Rscript -e 'install.packages(c("devtools"))'
  - Rscript -e 'devtools::install_deps(dependencies = TRUE)'
  - Rscript -e 'devtools::document(); devtools::test()'

script:
  - R CMD build .
  - R CMD check *tar.gz
  
after_success:
  - Rscript -e 'covr::codecov(token="7b481576-694c-4591-8370-64f61df55bdc")'